### ISSUE TITLE
Release of other DA prompts and datasets

### ISSUE THREAD

**Issue by christine1729** [KomeijiForce/CoTAM#1]
Hi, thanks for the great work. Just curious, 
1. will the prompts and their corresponding datasets mentioned in the paper be released soon? 
2. I also found section 5.2 very interesting, are the PCA and decision boundaries consistent for different classification tasks? Thanks!

**Comment by KomeijiForce** [comment]
Thanks for your favor on our work!
1. Yes, you can now find the prompts in the Appendix, and we will release the corresponding dataset when we unify the code for different datasets.
2. Yes! PCA results are generally consistent for other text classification tasks as shown in the Figures below. Positive-negative switching is the most obvious as they are antonym labels. 
![cotam_pca tweetemo](https://github.com/KomeijiForce/CoTAM/assets/116973827/11246ad3-bf45-4c6a-9163-8c3264447b53)
![cotam_pca ag_news](https://github.com/KomeijiForce/CoTAM/assets/116973827/ad48805e-7745-4313-b246-a0a9f5dde198)
